server:
  port: 8082

spring:
  application:
    name: producer

  kafka:
    bootstrap-servers: localhost:9092

  datasource:
    url: jdbc:h2:mem:pedidosdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true