spring:
  server:
    port: 8081
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: meu-grupo
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer